language: node_js
node_js:
  - "node"

script:
  - yarn build-storybook
  - yarn build
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./storybook-static
  on:
    branch: master
